name: Sync to target repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to target repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote add target https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/developeremaar/case-management-vercel.git

          git push target main:main --force
